/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{ts,tsx,js,jsx}'],
  theme: {
    extend: {
      fontFamily: {
        display: ['"Playfair Display"', 'Georgia', 'serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
      },
      colors: {
        cream: {
          50:  '#FEFAF5',
          100: '#FDF6EC',
          200: '#FAF0DC',
          300: '#F5E6C8',
          400: '#EEDBB0',
          500: '#E4CC94',
        },
        terracotta: {
          50:  '#FDF2EE',
          100: '#FAE2D9',
          200: '#F5C3AF',
          300: '#EEA080',
          400: '#E47C52',
          500: '#D96C4A',
          600: '#C55A38',
          700: '#A6472C',
          800: '#833723',
          900: '#61281A',
        },
        sage:  { 500: '#7A8C6E', 600: '#6A7A5E', 700: '#5A6A4E' },
        slate: { 700: '#374151', 800: '#1F2937', 900: '#111827' },
        border: 'hsl(var(--border))',
        input:  'hsl(var(--input))',
        ring:   'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary:   { DEFAULT: 'hsl(var(--primary))',   foreground: 'hsl(var(--primary-foreground))' },
        secondary: { DEFAULT: 'hsl(var(--secondary))', foreground: 'hsl(var(--secondary-foreground))' },
        destructive:{ DEFAULT: 'hsl(var(--destructive))',foreground: 'hsl(var(--destructive-foreground))' },
        muted:   { DEFAULT: 'hsl(var(--muted))',   foreground: 'hsl(var(--muted-foreground))' },
        accent:  { DEFAULT: 'hsl(var(--accent))',  foreground: 'hsl(var(--accent-foreground))' },
        card:    { DEFAULT: 'hsl(var(--card))',    foreground: 'hsl(var(--card-foreground))' },
        popover: { DEFAULT: 'hsl(var(--popover))', foreground: 'hsl(var(--popover-foreground))' },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': { from:{ height:'0' }, to:{ height:'var(--radix-accordion-content-height)' } },
        'accordion-up':   { from:{ height:'var(--radix-accordion-content-height)' }, to:{ height:'0' } },
        fadeIn:           { from:{ opacity:'0', transform:'translateY(8px)' }, to:{ opacity:'1', transform:'translateY(0)' } },
        slideIn:          { from:{ opacity:'0', transform:'translateX(-12px)' }, to:{ opacity:'1', transform:'translateX(0)' } },
        pulse:            { '0%,100%':{ opacity:'1' }, '50%':{ opacity:'.5' } },
        scaleIn:          { from:{ opacity:'0', transform:'scale(0.95)' }, to:{ opacity:'1', transform:'scale(1)' } },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up':   'accordion-up 0.2s ease-out',
        'fade-in':        'fadeIn 0.4s ease-out',
        'slide-in':       'slideIn 0.3s ease-out',
        'scale-in':       'scaleIn 0.2s ease-out',
      },
    },
  },
  plugins: [
    require('tailwindcss-animate'),
  ],
};
